[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = ["npm install", "npx prisma generate", "python3 -m venv venv", "venv/bin/pip install openpyxl"]

[start]
cmd = "npm run start"
